export const words = {
  futureDesignQuotes: [
    "Designing the future, one idea at a time.",
    "Innovation starts with future-focused design.",
    "The future is crafted by bold designs.",
    "Design today, inspire tomorrow.",
    "Shaping the future through creativity.",
    "Future design: where imagination meets reality.",
    "Tomorrow’s world begins with today’s design.",
    "In design, we trust the future.",
    "Crafting the blueprint of tomorrow.",
    "Design for the future, live in the present.",
  ],
  welcomeTranslations: [
    "Welcome",
    "Bienvenido",
    "Bienvenue",
    "Willkommen",
    "Benvenuto",
    "Bem-vindo",
    "Welkom",
    "ようこそ",
    "欢迎",
    "환영합니다",
    "أهلاً وسهلاً",
    "Добро пожаловать",
    "स्वागत है",
    "Välkommen",
    "Hoş geldiniz",
    "Καλώς ήρθατε",
    "Tervetuloa",
    "Velkommen",
    "Velkommen",
  ],
};

export const animationVariants = {
  hidden: { opacity: 0, y: 10 },
  visible: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -10 },
};
